################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils/src \
tools/scpi-parser/libscpi/test \
tools/scpi-parser/libscpi/src \
tools/scpi-parser/examples/test-tcp-srq \
tools/scpi-parser/examples/test-tcp \
tools/scpi-parser/examples/test-parser \
tools/scpi-parser/examples/test-interactive \
tools/scpi-parser/examples/test-LwIP-netconn \
tools/scpi-parser/examples/test-CVI_w_GUI \
tools/scpi-parser/examples/common \
tools/lcm/test/c \
tools/lcm/liblcm-test \
tools/lcm/lcmgen \
tools/lcm/lcm-python \
tools/lcm/lcm-lua \
tools/lcm/lcm-logger \
tools/lcm/lcm-lite \
tools/lcm/lcm \
tools/lcm/lcm/lcmtypes \
tools/lcm/examples/c \
tools/lcm/WinSpecific/getopt \
target/mcu/samd21 \
target/mcu/samd20 \
target/mcu/linux \
target/mcu/efm32lg990f256 \
target/mcu/atmega1281 \
target/if/native \
target/if/at86rf230 \
target/if/at86rf212b \
target/if/at86rf212 \
target/bsp/x86 \
target/bsp/samd20xpro_rf212b \
target/bsp/samd20xpro_rf212 \
target/bsp/efm32stk3600 \
target/bsp \
target/bsp/atany900_pro5 \
target/bsp/atany900_pro3 \
target/bsp/atany900_basic \
target/bsp/atany900 \
target/arch/arm/cm3/silabs/device/efm32lg/startup/GCC \
target/arch/arm/cm3/silabs/device/efm32lg/src \
target/arch/arm/cm3/silabs/device/common/src \
target/arch/arm/cm0plus/atmel/device/utils/src \
target/arch/arm/cm0plus/atmel/device/samd21/startup/IAR \
target/arch/arm/cm0plus/atmel/device/samd21/startup/GCC \
target/arch/arm/cm0plus/atmel/device/samd21/src \
target/arch/arm/cm0plus/atmel/device/samd20/startup/IAR \
target/arch/arm/cm0plus/atmel/device/samd20/startup/GCC \
target/arch/arm/cm0plus/atmel/device/samd20/src \
target/arch/arm/cm0plus/atmel/device/common/src \
emb6/src/tport \
emb6/src/net/slip \
emb6/src/net/sicslowpan \
emb6/src/net/rpl \
emb6/src/net/ipv6 \
emb6/src/net/ipv6/multicast \
emb6/src/net/dtls/sha2 \
emb6/src/net/dtls \
emb6/src/net/dtls/ecc \
emb6/src/net/dtls/aes \
emb6/src/mac \
emb6/src/mac/llsec \
emb6/src/apl/rest-engine \
emb6/src/apl/er-coap \
emb6 \
demo/udp_alive \
demo/sniffer \
demo/extif \
demo/dtls/server \
demo/dtls/client \
demo \
demo/coap/server/resources \
demo/coap/server/resources/old\ res \
demo/coap/server \
demo/coap/client \
demo/aptb/server \
demo/aptb/client \
build/dc_stk3600/utils/src \
build/dc_stk3600/target/mcu/efm32lg990f256 \
build/dc_stk3600/target/if/at86rf212b \
build/dc_stk3600/target/bsp/efm32stk3600 \
build/dc_stk3600/target/bsp \
build/dc_stk3600/target/arch/arm/cm3/silabs/device/efm32lg/src \
build/dc_stk3600/target/arch/arm/cm3/silabs/device/common/src \
build/dc_stk3600/emb6/src/tport \
build/dc_stk3600/emb6/src/net/sicslowpan \
build/dc_stk3600/emb6/src/net/rpl \
build/dc_stk3600/emb6/src/net/ipv6 \
build/dc_stk3600/emb6/src/net/dtls/sha2 \
build/dc_stk3600/emb6/src/net/dtls \
build/dc_stk3600/emb6/src/net/dtls/ecc \
build/dc_stk3600/emb6/src/net/dtls/aes \
build/dc_stk3600/emb6/src/mac \
build/dc_stk3600/emb6/src/mac/llsec \
build/dc_stk3600/emb6/src/apl/rest-engine \
build/dc_stk3600/emb6/src/apl/er-coap \
build/dc_stk3600/emb6 \
build/dc_stk3600/demo/dtls/client \
build/dc_stk3600/demo \
build/dc_stk3600 \
.sconf_temp \

